#!/usr/bin/env python3
"""
ASO Pre-flight & Post-flight Validator

MUST be run before writing any store listing content and after generating it.
Catches the exact mistakes that were made in previous sessions:
  1. Skipping existing scripts (fabricating data instead)
  2. Missing volume estimation (writing listings without demand data)
  3. Pipeline CSVs without volume integration
  4. Listing keywords not backed by any data source
  5. Titles/descriptions not validated against real data

Usage::

    # Before starting ASO work (pre-flight check)
    python3 py/aso/aso-preflight.py --pre

    # After generating listing content (post-flight validation)
    python3 py/aso/aso-preflight.py --post

    # Full check (both)
    python3 py/aso/aso-preflight.py --full

    # Generate a checklist report
    python3 py/aso/aso-preflight.py --report
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))

from _teamz_config import load_runtime  # noqa: E402

_CFG = load_runtime(
    os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "_teamz_config.py")
)
_DATA_DIR = Path(
    os.environ.get("TEAMZ_DATA_DIR", "")
    or _CFG.get("data_dir", "")
    or str(Path(_CFG["host_site_root"]) / "automation_data")
)
_AUTOMATION_PY = Path(os.path.dirname(os.path.abspath(__file__))).parent


# ── Pre-flight checks ────────────────────────────────────────────────────────

def check_scripts_exist() -> list[dict]:
    """Verify all required automation scripts exist."""
    required = {
        "aso/aso-keywords.py": "Keyword discovery (autocomplete, expand, trending)",
        "aso/aso-competitors.py": "Competitor analysis (find, matrix, keywords, gaps)",
        "aso/aso-metadata.py": "Metadata audit and scoring",
        "aso/aso-keyword-pipeline.py": "Scored CSV generation pipeline",
        "aso/aso-reviews.py": "Review sentiment analysis",
        "aso/aso-track.py": "Rank tracking",
        "aso/aso-guide.py": "ASO education and prompt generator",
        "build-keyword-volume.py": "Volume estimation (Bing + Trends + autocomplete)",
        "build-keyword-intel.py": "Keyword intelligence (GSC + intent)",
        "build-competitor-gaps.py": "SEO competitor gap analysis",
        "build-play-console.py": "Play Console listing pull/push",
        "seo-keyword-engine.py": "Full SEO + ASO keyword audit engine",
    }
    results = []
    for script, purpose in required.items():
        path = _AUTOMATION_PY / script
        exists = path.exists()
        results.append({
            "check": f"Script exists: {script}",
            "status": "PASS" if exists else "FAIL",
            "detail": purpose if exists else f"MISSING: {path}",
        })
    return results


def check_env_configured() -> list[dict]:
    """Verify .teamz-automation.env has required ASO fields."""
    results = []
    env_vars = {
        "TEAMZ_ASO_KEYWORDS": "Seed keywords for pipeline",
        "TEAMZ_APP_IDS": "Apple numeric app ID",
        "TEAMZ_PLAY_PACKAGE_NAME": "Android package name",
        "TEAMZ_DATA_DIR": "Output directory for CSVs",
    }
    for var, purpose in env_vars.items():
        value = os.environ.get(var, "")
        has_value = bool(value.strip())
        results.append({
            "check": f"Env var: {var}",
            "status": "PASS" if has_value else "WARN",
            "detail": f"Set to: {value[:50]}..." if has_value else f"NOT SET — needed for: {purpose}",
        })
    return results


def check_data_files_exist() -> list[dict]:
    """Check if required data files have been generated by scripts."""
    files = {
        "master_keywords.csv": ("aso-keyword-pipeline.py", "Scored keyword CSVs"),
        "ios_keywords.csv": ("aso-keyword-pipeline.py", "iOS keyword CSVs"),
        "keyword-competitive-analysis.json": ("custom per-keyword analysis", "Per-keyword competition data"),
        "aso-pipeline-latest.json": ("aso-keyword-pipeline.py", "Pipeline run metadata"),
    }
    results = []
    for filename, (source_script, purpose) in files.items():
        path = _DATA_DIR / filename
        exists = path.exists()
        detail = ""
        if exists:
            stat = path.stat()
            age_hours = (datetime.now().timestamp() - stat.st_mtime) / 3600
            detail = f"Age: {age_hours:.0f}h, Size: {stat.st_size:,} bytes"
            if age_hours > 168:  # 1 week
                detail += " ⚠️ STALE (>1 week old)"
        else:
            detail = f"MISSING — run: python3 py/{source_script}"
        results.append({
            "check": f"Data file: {filename}",
            "status": "PASS" if exists else "FAIL",
            "detail": detail,
        })
    return results


def check_volume_data_exists() -> list[dict]:
    """Check if build-keyword-volume.py was used (the #1 mistake from previous session)."""
    results = []

    # Check if pipeline JSON mentions volume estimation
    pipeline_json = _DATA_DIR / "aso-pipeline-latest.json"
    if pipeline_json.exists():
        with open(pipeline_json) as f:
            meta = json.load(f)
        has_volume = meta.get("volume_estimation") == "build-keyword-volume.py"
        results.append({
            "check": "Pipeline used build-keyword-volume.py",
            "status": "PASS" if has_volume else "FAIL",
            "detail": "Volume estimation integrated" if has_volume else
                      "⚠️ Pipeline ran WITHOUT volume data. Scores will be clustered and unreliable. "
                      "Re-run pipeline after fixing integration.",
        })
    else:
        results.append({
            "check": "Pipeline used build-keyword-volume.py",
            "status": "FAIL",
            "detail": "Pipeline hasn't been run yet. Run: python3 py/aso/aso-keyword-pipeline.py",
        })

    # Check if keyword-competitive-analysis.json has Bing/Trends data
    comp_json = _DATA_DIR / "keyword-competitive-analysis.json"
    if comp_json.exists():
        with open(comp_json) as f:
            data = json.load(f)
        results_list = data.get("results", [])
        has_any_volume = any(
            r.get("bing_volume") or r.get("trends_score")
            for r in results_list
        )
        results.append({
            "check": "Competitive analysis has volume/trends data",
            "status": "PASS" if has_any_volume else "WARN",
            "detail": f"{len(results_list)} keywords analyzed" if has_any_volume else
                      "No volume data in competitive analysis — was build-keyword-volume.py run on these keywords?",
        })

    return results


# ── Post-flight checks ───────────────────────────────────────────────────────

def check_listing_exists() -> list[dict]:
    """Check if the listing JSON was generated."""
    results = []
    # Check for en-US listing (glob pattern — filename varies per project)
    en_listings = list(_DATA_DIR.glob("play-listing-*-en-US.json"))
    results.append({
        "check": "English listing JSON (play-listing-*-en-US.json)",
        "status": "PASS" if en_listings else "FAIL",
        "detail": f"{en_listings[0].name} ({en_listings[0].stat().st_size:,} bytes)" if en_listings else "MISSING",
        })
    return results


def check_listing_has_data_rationale() -> list[dict]:
    """Check if listing decisions cite real data sources (not assumptions)."""
    results = []
    en_files = list(_DATA_DIR.glob("play-listing-*-en-US.json"))
    listing_path = en_files[0] if en_files else None
    if not listing_path:
        return [{"check": "Listing has data rationale", "status": "FAIL", "detail": "Listing file missing"}]

    with open(listing_path) as f:
        listing = json.load(f)

    # Check _data_source field exists and mentions real scripts
    data_source = listing.get("_data_source", "")
    real_sources = ["build-keyword-volume", "Google Trends", "keyword-competitive-analysis",
                    "aso-keyword-pipeline", "aso-competitors", "Bing"]
    sources_cited = [s for s in real_sources if s.lower() in data_source.lower()]
    results.append({
        "check": "Listing cites data sources",
        "status": "PASS" if len(sources_cited) >= 2 else "FAIL",
        "detail": f"Sources: {', '.join(sources_cited)}" if sources_cited else
                  "⚠️ No data sources cited. Listing may be based on assumptions, not data.",
    })

    # Check _title_rationale mentions actual numbers
    title_rationale = listing.get("_title_rationale", "")
    has_numbers = any(char.isdigit() for char in title_rationale)
    results.append({
        "check": "Title rationale has real numbers",
        "status": "PASS" if has_numbers else "FAIL",
        "detail": title_rationale[:100] + "..." if title_rationale else
                  "⚠️ No title rationale. Was the title chosen based on data or guessed?",
    })

    return results


def check_char_limits() -> list[dict]:
    """Validate all character limits across all locales."""
    results = []

    # English listing
    listing_path = _DATA_DIR / "play-listing-*-en-US.json"
    if listing_path.exists():
        with open(listing_path) as f:
            en = json.load(f)
        title_ok = len(en.get("title", "")) <= 30
        short_ok = len(en.get("shortDescription", "")) <= 80
        desc_ok = len(en.get("fullDescription", "")) <= 4000
        results.append({
            "check": "English title ≤30 chars",
            "status": "PASS" if title_ok else "FAIL",
            "detail": f"'{en['title']}' ({len(en['title'])} chars)",
        })
        results.append({
            "check": "English short desc ≤80 chars",
            "status": "PASS" if short_ok else "FAIL",
            "detail": f"{len(en.get('shortDescription', ''))} chars",
        })
        results.append({
            "check": "English full desc ≤4000 chars",
            "status": "PASS" if desc_ok else "FAIL",
            "detail": f"{len(en.get('fullDescription', ''))} chars",
        })

    # All locales
    locales_path = _DATA_DIR / "play-store-listings-all-locales.json"
    if locales_path.exists():
        with open(locales_path) as f:
            locales = json.load(f)
        title_fails = [k for k, v in locales.items() if len(v.get("title", "")) > 30]
        short_fails = [k for k, v in locales.items() if len(v.get("shortDescription", "")) > 80]
        results.append({
            "check": f"All {len(locales)} locale titles ≤30 chars",
            "status": "PASS" if not title_fails else "FAIL",
            "detail": f"Failing: {title_fails}" if title_fails else "All pass",
        })
        results.append({
            "check": f"All {len(locales)} locale short descs ≤80 chars",
            "status": "PASS" if not short_fails else "FAIL",
            "detail": f"Failing: {short_fails}" if short_fails else "All pass",
        })

    # Full descriptions
    descs_path = _DATA_DIR / "play-store-full-descriptions-all-locales.json"
    if descs_path.exists():
        with open(descs_path) as f:
            descs = json.load(f)
        desc_fails = [k for k, v in descs.items() if len(v) > 4000]
        results.append({
            "check": f"All {len(descs)} locale descriptions ≤4000 chars",
            "status": "PASS" if not desc_fails else "FAIL",
            "detail": f"Failing: {desc_fails}" if desc_fails else "All pass",
        })

    return results


def check_keyword_coverage() -> list[dict]:
    """Check if listing contains keywords from the scored data."""
    results = []
    listing_path = _DATA_DIR / "play-listing-*-en-US.json"
    csv_path = _DATA_DIR / "master_keywords.csv"

    if not listing_path.exists() or not csv_path.exists():
        return [{"check": "Keyword coverage", "status": "SKIP", "detail": "Listing or CSV missing"}]

    with open(listing_path) as f:
        listing = json.load(f)
    desc = listing.get("fullDescription", "").lower()
    title = listing.get("title", "").lower()
    short = listing.get("shortDescription", "").lower()
    combined = title + " " + short + " " + desc

    # Load top keywords from CSV
    top_kws = []
    with open(csv_path) as f:
        for i, row in enumerate(csv.DictReader(f)):
            if i >= 20:
                break
            top_kws.append(row["keyword"])

    # Check coverage against CSV top-20
    covered_csv = 0
    for kw in top_kws:
        words = kw.lower().split()
        if all(w in combined for w in words):
            covered_csv += 1

    pct_csv = (covered_csv / len(top_kws) * 100) if top_kws else 0
    results.append({
        "check": f"Top-20 CSV keywords in listing",
        "status": "PASS" if pct_csv >= 60 else ("WARN" if pct_csv >= 40 else "WARN"),
        "detail": f"{covered_csv}/{len(top_kws)} keywords ({pct_csv:.0f}%) — NOTE: CSV may contain noise. Check tags-based coverage below.",
    })

    # Also check against listing's own tags (curated, relevant keywords)
    tags = listing.get("tags", [])
    if tags:
        covered_tags = 0
        for tag in tags:
            words = tag.lower().split()
            if all(w in combined for w in words):
                covered_tags += 1
        pct_tags = (covered_tags / len(tags) * 100) if tags else 0
        results.append({
            "check": f"Listing tags ({len(tags)}) present in content",
            "status": "PASS" if pct_tags >= 80 else ("WARN" if pct_tags >= 60 else "FAIL"),
            "detail": f"{covered_tags}/{len(tags)} tags ({pct_tags:.0f}%) have all words in title+short+desc",
        })

    return results


def check_release_notes() -> list[dict]:
    """Validate release notes JSON exists, all locales ≤500 chars, and paste file is generated."""
    results = []

    rn_files = list(_DATA_DIR.glob("release-notes-*.json"))
    if not rn_files:
        results.append({
            "check": "Release notes JSON exists",
            "status": "FAIL",
            "detail": "No release-notes-*.json in automation_data/. "
                      "AI agent must generate it with version + all locale keys, each ≤500 chars.",
        })
        return results

    rn_path = rn_files[0]
    with open(rn_path) as f:
        rn = json.load(f)

    version = rn.get("version", "")
    locales = {k: v for k, v in rn.items() if k != "version"}

    results.append({
        "check": f"Release notes JSON exists (v{version})",
        "status": "PASS",
        "detail": f"{rn_path.name}: {len(locales)} locales",
    })

    # Check locale count
    expected_min = 30  # at least 30 locales expected
    results.append({
        "check": f"Release notes locale count ≥{expected_min}",
        "status": "PASS" if len(locales) >= expected_min else "WARN",
        "detail": f"{len(locales)} locales" + ("" if len(locales) >= expected_min
                  else f" — expected ≥{expected_min}. Missing translations?"),
    })

    # Check char limits (Play Console = 500 chars per locale)
    over_limit = [(k, len(v)) for k, v in locales.items() if len(v) > 500]
    results.append({
        "check": "Release notes all locales ≤500 chars",
        "status": "PASS" if not over_limit else "FAIL",
        "detail": ("All pass" if not over_limit
                   else "OVER LIMIT: " + ", ".join(f"{k} ({c} chars)" for k, c in over_limit)),
    })

    # Check paste file exists
    paste_files = list(_DATA_DIR.glob("release-notes-*-paste.txt"))
    results.append({
        "check": "Release notes paste file (.txt with <locale> tags)",
        "status": "PASS" if paste_files else "WARN",
        "detail": (paste_files[0].name if paste_files
                   else "Missing. Run: python3 py/aso/aso-copy-helper.py to generate it"),
    })

    return results


def check_no_fabricated_scores() -> list[dict]:
    """Detect signs of fabricated/hand-written CSVs (the original sin)."""
    results = []
    csv_path = _DATA_DIR / "master_keywords.csv"
    if not csv_path.exists():
        return [{"check": "CSV authenticity", "status": "SKIP", "detail": "CSV missing"}]

    rows = []
    with open(csv_path) as f:
        for row in csv.DictReader(f):
            rows.append(row)

    scores = [float(r["score"]) for r in rows]
    unique_scores = len(set(round(s, 4) for s in scores))

    # Red flags for fabricated data:
    # 1. Too few unique scores (< 10) means scores were hand-assigned
    # 2. Scores are suspiciously round (all end in .0 or .5)
    # 3. Very few rows (< 50) means keywords were hand-picked, not discovered
    red_flags = []
    if unique_scores < 10:
        red_flags.append(f"Only {unique_scores} unique score values (expected 20+ from real data)")
    if len(rows) < 50:
        red_flags.append(f"Only {len(rows)} keywords (expected 200+ from pipeline)")
    round_scores = sum(1 for s in scores if s == round(s, 1))
    if round_scores / len(scores) > 0.8:
        red_flags.append(f"{round_scores}/{len(scores)} scores are suspiciously round")

    # Check if pipeline metadata exists and matches CSV
    pipeline_json = _DATA_DIR / "aso-pipeline-latest.json"
    if pipeline_json.exists():
        with open(pipeline_json) as f:
            meta = json.load(f)
        csv_count = len(rows)
        meta_count = meta.get("total_keywords", 0)
        if abs(csv_count - meta_count) > 10:
            red_flags.append(
                f"CSV has {csv_count} rows but pipeline metadata says {meta_count} — "
                f"CSV may have been manually edited"
            )

    if red_flags:
        results.append({
            "check": "CSV data authenticity",
            "status": "FAIL",
            "detail": "⚠️ POSSIBLE FABRICATION: " + "; ".join(red_flags),
        })
    else:
        results.append({
            "check": "CSV data authenticity",
            "status": "PASS",
            "detail": f"{len(rows)} keywords, {unique_scores} unique scores — looks like real pipeline output",
        })

    return results


# ── Report ────────────────────────────────────────────────────────────────────

def run_checks(mode: str) -> list[dict]:
    """Run all checks for the given mode."""
    all_results = []

    if mode in ("pre", "full"):
        all_results.append(("SCRIPTS AVAILABLE", check_scripts_exist()))
        all_results.append(("ENVIRONMENT", check_env_configured()))
        all_results.append(("DATA FILES", check_data_files_exist()))
        all_results.append(("VOLUME DATA (critical)", check_volume_data_exists()))
        all_results.append(("CSV AUTHENTICITY", check_no_fabricated_scores()))

    if mode in ("post", "full"):
        all_results.append(("LISTING FILES", check_listing_exists()))
        all_results.append(("DATA RATIONALE", check_listing_has_data_rationale()))
        all_results.append(("CHARACTER LIMITS", check_char_limits()))
        all_results.append(("RELEASE NOTES", check_release_notes()))
        all_results.append(("KEYWORD COVERAGE", check_keyword_coverage()))

    return all_results


def print_report(sections: list[tuple[str, list[dict]]]):
    """Print the validation report."""
    total_pass = 0
    total_fail = 0
    total_warn = 0

    print(f"\n{'=' * 70}")
    print(f"  ASO PRE-FLIGHT / POST-FLIGHT VALIDATION")
    print(f"  {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}")
    print(f"{'=' * 70}")

    for section_name, checks in sections:
        print(f"\n  ── {section_name} ──")
        for check in checks:
            status = check["status"]
            icon = "✅" if status == "PASS" else ("⚠️" if status == "WARN" else ("⏭️" if status == "SKIP" else "❌"))
            if status == "PASS":
                total_pass += 1
            elif status == "FAIL":
                total_fail += 1
            elif status == "WARN":
                total_warn += 1
            print(f"    {icon} {check['check']}")
            if check["detail"]:
                print(f"       {check['detail']}")

    total = total_pass + total_fail + total_warn
    print(f"\n{'─' * 70}")
    print(f"  SUMMARY: {total_pass} passed, {total_fail} failed, {total_warn} warnings (of {total} checks)")

    if total_fail > 0:
        print(f"\n  ❌ BLOCKING: Fix {total_fail} failure(s) before writing/publishing store listing.")
        print(f"     DO NOT write listing content until all FAIL checks pass.")
    elif total_warn > 0:
        print(f"\n  ⚠️ PROCEED WITH CAUTION: {total_warn} warning(s) — review before publishing.")
    else:
        print(f"\n  ✅ ALL CLEAR: Safe to write/publish store listing content.")

    print(f"{'=' * 70}\n")

    # Write report JSON
    report = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "summary": {"pass": total_pass, "fail": total_fail, "warn": total_warn, "total": total},
        "sections": [
            {"name": name, "checks": checks} for name, checks in sections
        ],
    }
    report_path = _DATA_DIR / "aso-preflight-report.json"
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(json.dumps(report, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"  Report saved: {report_path}")

    return total_fail == 0


def main():
    parser = argparse.ArgumentParser(
        description="ASO pre-flight and post-flight validation. Run before AND after writing store listings.",
    )
    mx = parser.add_mutually_exclusive_group(required=True)
    mx.add_argument("--pre", action="store_true", help="Pre-flight: check scripts, env, data files, volume data")
    mx.add_argument("--post", action="store_true", help="Post-flight: check listing files, rationale, char limits, keywords")
    mx.add_argument("--full", action="store_true", help="Run all checks (pre + post)")
    mx.add_argument("--report", action="store_true", help="Same as --full, generates report JSON")
    args = parser.parse_args()

    if args.pre:
        mode = "pre"
    elif args.post:
        mode = "post"
    else:
        mode = "full"

    sections = run_checks(mode)
    success = print_report(sections)
    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()
